[workspace]
members = [
  "common",
  "nrf52840",
  "python",
]
default-members = ["common", "python"]
resolver = "2"

[workspace.dependencies]
chrono = { version = "0.4.38", default-features = false }

[profile.release]
debug = 2
