[project]
name = "yaroc"  # Required
version = "0.1"
authors = [
  {name = "Lukáš Poláček", email = "lukas@polacek.email" }
]
description = "Yet Another ROC"
keywords = ["orienteering", "online control"]
requires-python = ">=3.7"

dependencies = [
    "dbus-python",
    "paho-mqtt",
    "requests",
    "sportident",
]

[project.optional-dependencies] # Optional
dev = ["black", "mypy", "isort"]
test = ["pytest"]

[project.scripts]  # Optional
mqtt-bench = "yaroc.scripts.mqtt_bench:main"
mqtt-listener = "yaroc.scripts.mqtt_listener:main"
send-punch = "yaroc.scripts.send_punch:main"

[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100
