# TODO: add more info, see https://github.com/pypa/sampleproject/blob/main/pyproject.toml
[project]
name = "yaroc"  # Required
version = "0.1"
authors = [
  {name = "Lukáš Poláček", email = "lukas@polacek.email" }
]
description = "Yet Another ROC"
keywords = ["orienteering", "online control"]
requires-python = ">=3.10"

dependencies = [
    "dbus-python==1.3.*",
    "paho-mqtt==1.6.*",
    "requests==2.28.*",
    "sportident",
]

[project.optional-dependencies] # Optional
dev = ["black", "mypy", "isort", "flake8", "Flake8-pyproject"]
test = ["pytest"]

[project.scripts]  # Optional
mqtt-bench = "yaroc.scripts.mqtt_bench:main"
mqtt-listener = "yaroc.scripts.mqtt_listener:main"
send-punch = "yaroc.scripts.send_punch:main"

[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100

[tool.flake8]
max-line-length = 100
