[package]
edition = "2021"
name = "yaroc-nrf52840"
version = "0.1.0"
authors = ["Lukáš Poláček <lukas@polacek.email>"]
resolver = "2"
rust-version = "1.81"

[dependencies]
common = { path = "../common", features = ["defmt"] }

defmt = { workspace = true }
defmt-rtt = "0.4"
panic-probe = { version = "0.3", features = ["print-defmt"] }

embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
embedded-io = "0.6.1"
embedded-io-async = "0.6.1"

cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
embassy-executor = { version = "0.5", features = ["task-arena-size-8192", "arch-cortex-m", "executor-thread", "defmt", "integrated-timers", "executor-interrupt"] }
embassy-nrf = { version = "0.1.0", features = ["defmt", "nrf52840", "time-driver-rtc1", "gpiote", "unstable-pac", "time", "nfc-pins-as-gpio"] }
embassy-sync = "0.6.1"
embassy-time = { version = "0.3.2", features = ["defmt", "defmt-timestamp-uptime"] }

chrono = { workspace = true }
femtopb = { workspace = true }
heapless =  { workspace = true }
thiserror = { workspace = true }
