[package]
edition = "2021"
name = "yaroc-nrf52840"
version = "0.1.0"
authors = ["Lukáš Poláček <lukas@polacek.email>"]
resolver = "2"
rust-version = "1.81"

[features]
bluetooth-le = ["dep:nrf-softdevice"]

[dependencies]
yaroc-common = { path = "../common", features = ["defmt", "nrf"] }

defmt = { workspace = true }
defmt-rtt = "1.0"
panic-probe = { version = "1.0", features = ["print-defmt"] }

embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
embedded-io = "0.6.1"
embedded-io-async = "0.6.1"

cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7"
cortex-m-semihosting = "0.5.0"
embassy-executor = { workspace = true, features = ["arch-cortex-m", "defmt", "executor-interrupt"] }
embassy-futures = { workspace = true }
embassy-nrf = { workspace = true }
embassy-sync = { workspace = true }
embassy-time = { workspace = true, features = ["defmt", "defmt-timestamp-uptime"] }
nrf-softdevice = { version = "0.1.0", features = ["defmt", "nrf52840", "s140", "ble-peripheral", "critical-section-impl"], optional = true }

chrono = { workspace = true }
femtopb = { workspace = true }
heapless =  { workspace = true, features = ["defmt-03"] }
thiserror = { workspace = true }

[lib]
harness = false

[dev-dependencies]
defmt-test = "0.3"
static_cell = "2.1.0"

[[test]]
name = "bg77_sysinfo"
harness = false
