[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip nRF52840_xxAA"
# runner = ["probe-rs", "run", "--chip", "nRF52840_xxAA", "--log-format", "{t} {L} {s}"]

[build]
target = "thumbv7em-none-eabihf"
