[package]
name = "common"
version = "0.1.0"
edition = "2021"

[features]
default = []
defmt = ["dep:defmt"]

[dependencies]
chrono = { workspace = true }
defmt = { workspace = true, optional = true }
embassy-sync = { workspace = true }
femtopb = { workspace = true }
heapless =  { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
femtopb-build = "0.5.0"
