[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
defmt = { workspace = true }
heapless =  { workspace = true }
thiserror = { workspace = true }
