[package]
name = "common"
version = "0.1.0"
edition = "2021"

[features]
default = []
defmt = ["dep:defmt"]
std = ["embassy-executor/arch-std", "embassy-time/std"]

[dependencies]
chrono = { workspace = true }
defmt = { workspace = true, optional = true }
embassy-executor = { workspace = true }
embassy-sync = { workspace = true }
embassy-time = { workspace = true }
femtopb = { workspace = true }
heapless =  { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
critical-section = { version = "1", features = ["std"]}
embassy-futures = "0.1.1"

[build-dependencies]
femtopb-build = "0.5.0"
