[package]
name = "yaroc-python"
version = "0.1.14"
edition = "2021"
rust-version = "1.70"

[features]
default = ["receive"]
receive = ["yaroc-common/receive", "dep:meshtastic"]

[build-dependencies]
walkdir = "2.3.2"

[dependencies]
yaroc-common = { path = "../common", features = ["std"] }

chrono = { workspace = true, default-features = true }
femtopb = { workspace = true }
log = { workspace = true }
meshtastic = { workspace = true, optional = true }
pyo3 = { version = "0.23", features = ["extension-module", "chrono", "abi3-py311"] }
pyo3-log = "0.12.0"
regex = "1.11"
thiserror = { workspace = true, default-features = true }

[lib]
name = "yaroc_rs"
crate-type = ["cdylib", "rlib"]

[lints.clippy]
manual_range_contains = "allow"
