# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name:  Prepare
      run: |
        python -m pip install --upgrade pip
        python -m venv .venv
        sudo apt update && sudo apt install -y cargo libudev-dev protobuf-compiler libdbus-1-dev pkg-config
    - name: Rust
      run: |
        source .venv/bin/activate
        pip install maturin
        maturin develop
        pip install ".[dev]"
        pip install ".[test]"

    - name: Lint with ruff
      run: |
        source .venv/bin/activate
        # stop the build if there are Python syntax errors or undefined names
        ruff check . --select=E9,F63,F7,F82 --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        ruff check . --exit-zero --statistics
    - name: Test with pytest
      run: |
        source .venv/bin/activate
        pytest
